services:
  168cap:
    build: ../../apps/168cap
    container_name: 168cap
    restart: always
    ports:
      - "8000:80"
    env_file:
      - ../../apps/168cap/.env
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  168board:
    build: ../../apps/168board
    container_name: 168board
    restart: always
    ports:
      - "8011:80"
    env_file:
      - ../../apps/168board/.env
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
